language: cpp

compiler:
  - clang
  - gcc
 
before_install:
  - sudo easy_install cpp-coveralls

script:
  - cd ./test
  - make all

after_success:
  # Coverage
  - if [ "${USE_COVERAGE}" = '1' ]; then make send-coverage; fi

matrix:
  exclude:
    - compiler: clang
      env: USE_COVERAGE=1
